/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef nyan_CONSTANTS_H
#define nyan_CONSTANTS_H

#include "nyan_types.h"

namespace nyan {

class nyanConstants {
 public:
  nyanConstants();

  int32_t INT32CONSTANT;
};

extern const nyanConstants g_nyan_constants;

} // namespace

#endif
