/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "nyan_constants.h"

namespace nyan {

const nyanConstants g_nyan_constants;

nyanConstants::nyanConstants() {
  INT32CONSTANT = 9853;

}

} // namespace

